# 🌦️ Project DWH — Cuaca Kota Besar Indonesia 2023–2024
**ETL Pipeline Lengkap: Extract → Transform → Load → Periodic (Sync & Async)**

---
### Struktur Notebook
| Bagian | Isi |
|--------|-----|
| **STEP 0** | Setup & Konfigurasi |
| **STEP 1** | Extract Historis 2023–2024 |
| **STEP 2** | Periodic ETL (Simulasi) |
| **STEP 3** | Transform (Anomali, FE, Dimensi, Fact) |
| **STEP 4** | Load ke Supabase (DDL + to_sql + Verify) |

---
# STEP 0 — Setup & Konfigurasi

## 0.1 Install Library

In [1]:
!pip install requests pandas sqlalchemy psycopg2-binary numpy apscheduler -q
print("Semua library berhasil diinstall")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 31.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 4.0 MB/s eta 0:00:00
Semua library berhasil diinstall

## 0.2 Import Library

In [2]:
import requests
import pandas as pd
import numpy as np
import os
import time
import json
import logging
from datetime import datetime, timedelta
from sqlalchemy import create_engine, text

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
logger = logging.getLogger(__name__)
print("Import selesai")

Import selesai

## 0.3 Konfigurasi Global

> 🔑 **Isi `SUPABASE_URL` dengan connection string Supabase kamu.**
> Format: `postgresql://postgres.[project-ref]:[password]@aws-0-[region].pooler.supabase.com:5432/postgres`
> Cara dapatnya: Supabase Dashboard → Project Settings → Database → Connection String → Mode: **Transaction**

> ⚙️ **`ASYNC_MODE`**: set `False` untuk mode Colab biasa, `True` untuk deploy async 24/7

In [3]:
#  KONFIGURASI — Isi bagian ini sebelum menjalankan
SUPABASE_URL = "postgresql://postgres.pqjgzypewsmrwscbzhbv:d9cU++JybK9Mtt9@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"

# Mode operasi
ASYNC_MODE   = False   # False = Colab manual | True = async 24/7 via scheduler

# File staging lokal
CSV_BACKUP   = "raw_all_cities.csv"

# Konfigurasi 10 Kota
CITIES = [
    {"city":"Surabaya",   "lat":-7.2575,  "lon":112.7521, "province":"Jawa Timur",       "island":"Jawa",       "timezone":"WIB",  "tz_string":"Asia/Jakarta"},
    {"city":"Jakarta",    "lat":-6.2088,  "lon":106.8456, "province":"DKI Jakarta",      "island":"Jawa",       "timezone":"WIB",  "tz_string":"Asia/Jakarta"},
    {"city":"Bandung",    "lat":-6.9175,  "lon":107.6191, "province":"Jawa Barat",       "island":"Jawa",       "timezone":"WIB",  "tz_string":"Asia/Jakarta"},
    {"city":"Medan",      "lat": 3.5952,  "lon": 98.6722, "province":"Sumatra Utara",    "island":"Sumatra",    "timezone":"WIB",  "tz_string":"Asia/Jakarta"},
    {"city":"Semarang",   "lat":-6.9932,  "lon":110.4229, "province":"Jawa Tengah",      "island":"Jawa",       "timezone":"WIB",  "tz_string":"Asia/Jakarta"},
    {"city":"Makassar",   "lat":-5.1477,  "lon":119.4327, "province":"Sulawesi Selatan", "island":"Sulawesi",   "timezone":"WITA", "tz_string":"Asia/Makassar"},
    {"city":"Palembang",  "lat":-2.9761,  "lon":104.7754, "province":"Sumatra Selatan",  "island":"Sumatra",    "timezone":"WIB",  "tz_string":"Asia/Jakarta"},
    {"city":"Denpasar",   "lat":-8.6705,  "lon":115.2126, "province":"Bali",             "island":"Bali",       "timezone":"WITA", "tz_string":"Asia/Makassar"},
    {"city":"Yogyakarta", "lat":-7.7956,  "lon":110.3695, "province":"DIY",              "island":"Jawa",       "timezone":"WIB",  "tz_string":"Asia/Jakarta"},
    {"city":"Balikpapan", "lat":-1.2675,  "lon":116.8289, "province":"Kalimantan Timur", "island":"Kalimantan", "timezone":"WITA", "tz_string":"Asia/Makassar"},
]

API_URL    = "https://archive-api.open-meteo.com/v1/archive"
START_DATE = "2015-01-01"
END_DATE   = "2024-12-31"
VARIABLES  = [
    "temperature_2m", "apparent_temperature", "relative_humidity_2m",
    "dew_point_2m", "precipitation", "rain", "cloud_cover",
    "wind_speed_10m", "wind_direction_10m", "wind_gusts_10m",
    "shortwave_radiation", "sunshine_duration", "surface_pressure", "weather_code"
]

print(f"   Konfigurasi dimuat")
print(f"   Kota     : {len(CITIES)}")
print(f"   Variabel : {len(VARIABLES)}")
print(f"   Periode  : {START_DATE} s/d {END_DATE}")
print(f"   Mode     : {'ASYNC 24/7' if ASYNC_MODE else 'Colab Manual'}")

   Konfigurasi dimuat
   Kota     : 10
   Variabel : 14
   Periode  : 2015-01-01 s/d 2024-12-31
   Mode     : Colab Manual


# STEP 1 — Extract Data Historis 2023–2024

## 1.1 Fungsi Extract

In [4]:
# Fungsi inti extract 1 kota
def extract_one_city(city, start_date, end_date):
    """Ambil data cuaca 1 kota dari Open-Meteo API."""
    params = {
        "latitude"  : city["lat"],
        "longitude" : city["lon"],
        "start_date": start_date,
        "end_date"  : end_date,
        "hourly"    : VARIABLES,
        "timezone"  : city["tz_string"]
    }
    try:
        resp = requests.get(API_URL, params=params, timeout=60)
        if resp.status_code != 200:
            logger.warning(f"GAGAL: {city['city']} — HTTP {resp.status_code}")
            return None

        data   = resp.json()
        hourly = data["hourly"]
        df     = pd.DataFrame(hourly)

        df["city"]      = city["city"]
        df["province"]  = city["province"]
        df["island"]    = city["island"]
        df["timezone"]  = city["timezone"]
        df["latitude"]  = data["latitude"]
        df["longitude"] = data["longitude"]
        df["elevation"] = data["elevation"]

        logger.info(f"OK: {city['city']} — {len(df)} baris ({city['timezone']})")
        return df

    except Exception as e:
        logger.error(f"ERROR {city['city']}: {e}")
        return None


# Fungsi extract semua kota
def extract_all_cities(start_date=START_DATE, end_date=END_DATE, save=True):
    print('='*55)
    print('EXTRACT DATA CUACA')
    print(f'Periode : {start_date} s/d {end_date}')
    print(f'Kota    : {len(CITIES)} kota')
    print('='*55)

    frames = []
    for city in CITIES:
        print(f"  Mengambil {city['city']}...")
        df = extract_one_city(city, start_date, end_date)
        if df is not None:
            frames.append(df)
        time.sleep(30)   # jeda sopan ke API

    if not frames:
        print('GAGAL: tidak ada data berhasil diambil!')
        return None

    df_all = pd.concat(frames, ignore_index=True)

    print(f'\n Extract selesai!')
    print(f'   Total baris : {len(df_all):,}')
    print(f'   Total kolom : {len(df_all.columns)}')
    print(f'   Rentang     : {df_all["time"].min()} → {df_all["time"].max()}')

    if save:
        df_all.to_csv(CSV_BACKUP, index=False)
        print(f'   Tersimpan di: {CSV_BACKUP}')

    return df_all


# Fungsi CSV staging
def load_from_csv():
    if not os.path.exists(CSV_BACKUP):
        print(f' File CSV tidak ditemukan: {CSV_BACKUP}')
        return None
    df = pd.read_csv(CSV_BACKUP)
    print(f' Loaded dari CSV: {len(df):,} baris')
    return df


def append_new_data(df_new):
    if not os.path.exists(CSV_BACKUP):
        df_new.to_csv(CSV_BACKUP, index=False)
        print(f' Data pertama disimpan: {len(df_new):,} baris')
        return df_new

    df_old = pd.read_csv(CSV_BACKUP)
    df_combined = pd.concat([df_old, df_new], ignore_index=True)
    df_combined = df_combined.drop_duplicates(subset=["time","city"], keep="last")
    df_combined = df_combined.sort_values(["city","time"]).reset_index(drop=True)
    df_combined.to_csv(CSV_BACKUP, index=False)

    added = len(df_combined) - len(df_old)
    print(f' Append selesai: +{added:,} baris baru | total {len(df_combined):,} baris')
    return df_combined

print('Semua fungsi Extract siap!')

Semua fungsi Extract siap!

## 1.2 Jalankan Extract Historis

In [5]:
# Extract data 2023-2024
# Jika CSV sudah ada (misal rerun), langsung load dari CSV saja
if os.path.exists(CSV_BACKUP):
    print(f' CSV sudah ada → load dari lokal')
    df_all = load_from_csv()
else:
    print(' CSV belum ada → menjalankan extract dari API...')
    df_all = extract_all_cities()

if df_all is not None:
    print(f'\nPreview:')
    display(df_all.head(3))
    print(f'\nJumlah baris per kota:')
    print(df_all['city'].value_counts())

 CSV belum ada → menjalankan extract dari API...
=======================================================
EXTRACT DATA CUACA
Periode : 2015-01-01 s/d 2024-12-31
Kota    : 10 kota
=======================================================
  Mengambil Surabaya...
  Mengambil Jakarta...
  Mengambil Bandung...
  Mengambil Medan...
  Mengambil Semarang...
  Mengambil Makassar...
  Mengambil Palembang...
  Mengambil Denpasar...
  Mengambil Yogyakarta...
  Mengambil Balikpapan...

 Extract selesai!
   Total baris : 876,720
   Total kolom : 22
   Rentang     : 2015-01-01T00:00 → 2024-12-31T23:00
   Tersimpan di: raw_all_cities.csv

Preview:

,time,temperature_2m,apparent_temperature,relative_humidity_2m,dew_point_2m,precipitation,rain,cloud_cover,wind_speed_10m,wind_direction_10m,...,sunshine_duration,surface_pressure,weather_code,city,province,island,timezone,latitude,longitude,elevation
0,2015-01-01T00:00,25.2,29.8,90,23.3,0.3,0.3,100,7.2,252,...,0.0,1007.5,51,Surabaya,Jawa Timur,Jawa,WIB,-7.275922,112.785774,8.0
1,2015-01-01T01:00,24.9,29.6,91,23.4,0.4,0.4,100,7.6,262,...,0.0,1007.1,51,Surabaya,Jawa Timur,Jawa,WIB,-7.275922,112.785774,8.0
2,2015-01-01T02:00,24.9,29.4,91,23.4,0.3,0.3,100,8.7,275,...,0.0,1006.6,51,Surabaya,Jawa Timur,Jawa,WIB,-7.275922,112.785774,8.0

Jumlah baris per kota:
city
Surabaya      87672
Jakarta       87672
Bandung       87672
Medan         87672
Semarang      87672
Makassar      87672
Palembang     87672
Denpasar      87672
Yogyakarta    87672
Balikpapan    87672
Name: count, dtype: int64

# STEP 2 — Periodic ETL
Dua mode: **Simulasi manual** (Colab) dan **Async 24/7** (scheduler)

## 2.1 Fungsi Periodic ETL

In [6]:
# Extract mingguan
def extract_weekly_update(minggu_ke=0):
    """
    Ambil data 1 minggu dari anchor date 2024-12-31.
    minggu_ke=0 → minggu terakhir, minggu_ke=1 → seminggu sebelumnya, dst.
    """
    anchor     = datetime(2024, 12, 31)
    end_dt     = anchor - timedelta(weeks=minggu_ke)
    start_dt   = end_dt - timedelta(days=7)
    end_str    = end_dt.strftime('%Y-%m-%d')
    start_str  = start_dt.strftime('%Y-%m-%d')

    print(f'  Periode: {start_str} → {end_str}')
    return extract_all_cities(start_str, end_str, save=False)


# ETL Periodik Lengkap
def jalankan_etl_periodik(run_ke=1, minggu_ke=0, engine=None):
    """
    Satu siklus ETL periodik:
      1. Extract data mingguan
      2. Append ke CSV staging (deduplikasi)
      3. Backup file sementara
      4. (Opsional) Refresh Materialized View di Supabase

    Parameter engine opsional — hanya dipakai kalau sudah ada koneksi DB.
    """
    print('\n' + '='*55)
    print(f'ETL PERIODIK — RUN KE-{run_ke}')
    print(f'Waktu   : {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    print(f'Periode : minggu ke-{minggu_ke} dari anchor')
    print('='*55)

    try:
        # STEP 1 — Extract
        print('\n[1] Extract...')
        df_baru = extract_weekly_update(minggu_ke=minggu_ke)
        if df_baru is None or len(df_baru) == 0:
            print(' Extract gagal, skip run ini.')
            return False
        print(f' {len(df_baru):,} baris diterima')

        # STEP 2 — Append ke CSV
        print('\n[2] Append ke staging CSV...')
        df_combined = append_new_data(df_baru)

        # STEP 3 — Backup file sementara
        print('\n[3] Simpan backup...')
        ts   = datetime.now().strftime('%Y%m%d_%H%M%S')
        bkup = f'update_run{run_ke}_{ts}.csv'
        df_baru.to_csv(bkup, index=False)
        print(f' Backup: {bkup}')

        # STEP 4 — Refresh Materialized View (jika ada koneksi)
        if engine is not None:
            print('\n[4] Refresh Materialized View...')
            try:
                with engine.connect() as conn:
                    conn.execute(text("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_daily_summary"))
                    conn.execute(text("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_monthly_avg"))
                    conn.commit()
                print(' Materialized View diperbarui')
            except Exception as e:
                print(f'  MV refresh gagal (mungkin belum dibuat): {e}')

        print(f'\n RUN KE-{run_ke} SELESAI — {datetime.now().strftime("%H:%M:%S")}')
        return True

    except Exception as e:
        logger.error(f'ETL periodik gagal: {e}')
        return False

print('Fungsi Periodic ETL siap!')

Fungsi Periodic ETL siap!

## 2.2 Simulasi Periodik (Mode Colab Manual)

In [7]:
# Jalankan hanya jika ASYNC_MODE = False
if not ASYNC_MODE:
    JUMLAH_RUN = 3
    JEDA_DETIK = 10

    print('SIMULASI PERIODIC ETL')
    print(f'Anchor   : 2024-12-31')
    print(f'Run      : {JUMLAH_RUN}x (jeda {JEDA_DETIK} detik antar run)')
    print()

    for i in range(JUMLAH_RUN):
        sukses = jalankan_etl_periodik(run_ke=i+1, minggu_ke=i)
        if i < JUMLAH_RUN - 1 and sukses:
            print(f'\n  Menunggu {JEDA_DETIK} detik...')
            time.sleep(JEDA_DETIK)

    print('\n' + '='*55)
    print('SIMULASI SELESAI!')
    print(f'   {JUMLAH_RUN} run berhasil dieksekusi')
    print('='*55)
else:
    print('   ASYNC_MODE = True → skip simulasi manual')
    print('   Aktifkan scheduler di STEP 2.3')

SIMULASI PERIODIC ETL
Anchor   : 2024-12-31
Run      : 3x (jeda 10 detik antar run)


=======================================================
ETL PERIODIK — RUN KE-1
Waktu   : 2026-06-12 09:44:39
Periode : minggu ke-0 dari anchor
=======================================================

[1] Extract...
  Periode: 2024-12-24 → 2024-12-31
=======================================================
EXTRACT DATA CUACA
Periode : 2024-12-24 s/d 2024-12-31
Kota    : 10 kota
=======================================================
  Mengambil Surabaya...
  Mengambil Jakarta...
  Mengambil Bandung...
  Mengambil Medan...
  Mengambil Semarang...
  Mengambil Makassar...
  Mengambil Palembang...
  Mengambil Denpasar...
  Mengambil Yogyakarta...
  Mengambil Balikpapan...

 Extract selesai!
   Total baris : 1,920
   Total kolom : 22
   Rentang     : 2024-12-24T00:00 → 2024-12-31T23:00
 1,920 baris diterima

[2] Append ke staging CSV...
 Append selesai: +0 baris baru | total 876,720 baris

[3] Simpan backup...
 Backup: update_run1_20260612_095018.csv

 RUN KE-1 SELESAI — 09:50:18

  Menunggu 10 detik...

=======================================================
ETL PERIODIK — RUN KE-2
Waktu   : 2026-06-12 09:50:28
Periode : minggu ke-1 dari anchor
=======================================================

[1] Extract...
  Periode: 2024-12-17 → 2024-12-24
=======================================================
EXTRACT DATA CUACA
Periode : 2024-12-17 s/d 2024-12-24
Kota    : 10 kota
=======================================================
  Mengambil Surabaya...
  Mengambil Jakarta...
  Mengambil Bandung...
  Mengambil Medan...
  Mengambil Semarang...
  Mengambil Makassar...
  Mengambil Palembang...
  Mengambil Denpasar...
  Mengambil Yogyakarta...
  Mengambil Balikpapan...

 Extract selesai!
   Total baris : 1,920
   Total kolom : 22
   Rentang     : 2024-12-17T00:00 → 2024-12-24T23:00
 1,920 baris diterima

[2] Append ke staging CSV...
 Append selesai: +0 baris baru | total 876,720 baris

[3] Simpan backup...
 Backup: update_run2_20260612_095602.csv

 RUN KE-2 SELESAI — 09:56:02

  Menunggu 10 detik...

=======================================================
ETL PERIODIK — RUN KE-3
Waktu   : 2026-06-12 09:56:12
Periode : minggu ke-2 dari anchor
=======================================================

[1] Extract...
  Periode: 2024-12-10 → 2024-12-17
=======================================================
EXTRACT DATA CUACA
Periode : 2024-12-10 s/d 2024-12-17
Kota    : 10 kota
=======================================================
  Mengambil Surabaya...
  Mengambil Jakarta...
  Mengambil Bandung...
  Mengambil Medan...
  Mengambil Semarang...
  Mengambil Makassar...
  Mengambil Palembang...
  Mengambil Denpasar...
  Mengambil Yogyakarta...
  Mengambil Balikpapan...

 Extract selesai!
   Total baris : 1,920
   Total kolom : 22
   Rentang     : 2024-12-10T00:00 → 2024-12-17T23:00
 1,920 baris diterima

[2] Append ke staging CSV...
 Append selesai: +0 baris baru | total 876,720 baris

[3] Simpan backup...
 Backup: update_run3_20260612_100132.csv

 RUN KE-3 SELESAI — 10:01:32

=======================================================
SIMULASI SELESAI!
   3 run berhasil dieksekusi
=======================================================

## 2.3 Verifikasi Hasil Setelah Periodic

In [8]:
df_final = load_from_csv()

if df_final is not None:
    print('HASIL SETELAH PERIODIC ETL:')
    print(f'  Total baris : {len(df_final):,}')
    print(f'  Total kota  : {df_final["city"].nunique()}')
    print(f'  Dari        : {df_final["time"].min()}')
    print(f'  Sampai      : {df_final["time"].max()}')
    print(f'\nJumlah per kota:')
    print(df_final['city'].value_counts())

 Loaded dari CSV: 876,720 baris
HASIL SETELAH PERIODIC ETL:
  Total baris : 876,720
  Total kota  : 10
  Dari        : 2015-01-01T00:00
  Sampai      : 2024-12-31T23:00

Jumlah per kota:
city
Balikpapan    87672
Bandung       87672
Denpasar      87672
Jakarta       87672
Makassar      87672
Medan         87672
Palembang     87672
Semarang      87672
Surabaya      87672
Yogyakarta    87672
Name: count, dtype: int64

# STEP 3 — Transform

## 3.1 Load Raw Data

In [9]:
df = pd.read_csv(CSV_BACKUP)
print(f'Data dimuat: {len(df):,} baris, {len(df.columns)} kolom')
display(df.head(3))

Data dimuat: 876,720 baris, 22 kolom

,time,temperature_2m,apparent_temperature,relative_humidity_2m,dew_point_2m,precipitation,rain,cloud_cover,wind_speed_10m,wind_direction_10m,...,sunshine_duration,surface_pressure,weather_code,city,province,island,timezone,latitude,longitude,elevation
0,2015-01-01T00:00,24.6,30.5,99,24.5,0.0,0.0,100,2.9,240,...,0.0,999.3,3,Balikpapan,Kalimantan Timur,Kalimantan,WITA,-1.230228,116.85083,89.0
1,2015-01-01T01:00,25.4,30.3,88,23.3,0.0,0.0,100,5.3,242,...,0.0,998.3,3,Balikpapan,Kalimantan Timur,Kalimantan,WITA,-1.230228,116.85083,89.0
2,2015-01-01T02:00,25.4,30.0,87,23.0,0.0,0.0,100,6.0,253,...,0.0,997.8,3,Balikpapan,Kalimantan Timur,Kalimantan,WITA,-1.230228,116.85083,89.0

## 3.2 Cek Anomali & Handling

In [10]:
print('='*55)
print('LAPORAN ANOMALI DATA')
print('='*55)

# Missing values
null_counts = df.isnull().sum()
print(f'\n[1] Missing Values (kolom > 0):')
print(null_counts[null_counts > 0].to_string() if null_counts.sum() > 0 else ' Tidak ada missing value')

# Nilai negatif precipitation
neg_precip = df[df['precipitation'] < 0]
print(f'\n[2] Nilai Negatif Precipitation: {len(neg_precip)} baris')
if len(neg_precip) > 0:
    print(neg_precip[['time','city','precipitation']].head())

# Outlier suhu ekstrem (Indonesia: wajar 15–40°C)
outlier_suhu = df[(df['temperature_2m'] < 10) | (df['temperature_2m'] > 45)]
print(f'\n[3] Outlier Suhu (< 10°C atau > 45°C): {len(outlier_suhu)} baris')
if len(outlier_suhu) > 0:
    print(outlier_suhu[['time','city','temperature_2m']].head())

# Radiation 0 di jam siang (10–14)
df['_hour_tmp'] = pd.to_datetime(df['time']).dt.hour
anom_rad = df[(df['shortwave_radiation'] == 0) & df['_hour_tmp'].between(10, 14)]
print(f'\n[4] Radiasi 0 di Jam Siang (10-14): {len(anom_rad)} baris')
df.drop(columns=['_hour_tmp'], inplace=True)

print('\n Cek anomali selesai')

=======================================================
LAPORAN ANOMALI DATA
=======================================================

[1] Missing Values (kolom > 0):
 Tidak ada missing value

[2] Nilai Negatif Precipitation: 0 baris

[3] Outlier Suhu (< 10°C atau > 45°C): 0 baris

[4] Radiasi 0 di Jam Siang (10-14): 4 baris

 Cek anomali selesai

## 3.3 Integration

In [11]:
# Konversi waktu
df['time'] = pd.to_datetime(df['time'])
df['date'] = df['time'].dt.date
df['hour'] = df['time'].dt.hour

# Bersihkan nilai tidak wajar
df['precipitation'] = df['precipitation'].clip(lower=0)
df['rain']          = df['rain'].clip(lower=0)

print(' Integration selesai!')
print(df[['time','date','hour','city','temperature_2m','precipitation']].head())

 Integration selesai!
                 time        date  hour        city  temperature_2m  \
0 2015-01-01 00:00:00  2015-01-01     0  Balikpapan            24.6
1 2015-01-01 01:00:00  2015-01-01     1  Balikpapan            25.4
2 2015-01-01 02:00:00  2015-01-01     2  Balikpapan            25.4
3 2015-01-01 03:00:00  2015-01-01     3  Balikpapan            25.5
4 2015-01-01 04:00:00  2015-01-01     4  Balikpapan            25.3

   precipitation
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0

## 3.4 Feature Engineering

In [12]:
# 1. heat_index_diff
df['heat_index_diff'] = df['apparent_temperature'] - df['temperature_2m']

# 2. rain_intensity
def kategorikan_hujan(mm):
    if mm == 0:      return "Tidak Hujan"
    elif mm <= 2.5:  return "Hujan Ringan"
    elif mm <= 10:   return "Hujan Sedang"
    elif mm <= 50:   return "Hujan Lebat"
    else:            return "Hujan Ekstrem"
df['rain_intensity'] = df['precipitation'].apply(kategorikan_hujan)

# 3. is_rainy_hour
df['is_rainy_hour'] = df['precipitation'] > 0.1

# 4. wind_category
def kategorikan_angin(kmh):
    if kmh <= 20:   return "Tenang"
    elif kmh <= 40: return "Semilir"
    elif kmh <= 60: return "Kencang"
    else:           return "Berbahaya"
df['wind_category'] = df['wind_speed_10m'].apply(kategorikan_angin)

# 5. direction_label
def arah_angin(d):
    if d >= 315 or d < 45:  return "Utara"
    elif d < 135:            return "Timur"
    elif d < 225:            return "Selatan"
    else:                    return "Barat"
df['direction_label'] = df['wind_direction_10m'].apply(arah_angin)

# 6. gust_ratio & is_gust_extreme
df['gust_ratio']      = df['wind_gusts_10m'] / df['wind_speed_10m'].replace(0, 0.01)
df['is_gust_extreme'] = df['gust_ratio'] > 2

# 7. alert_hour (presipitasi tinggi + angin kencang)
df['alert_hour'] = ((df['precipitation'] > 5) & (df['wind_speed_10m'] > 20)).astype(int)

print('Feature Engineering selesai!')
print(df[['heat_index_diff','rain_intensity','wind_category','direction_label','is_gust_extreme']].head())

Feature Engineering selesai!
   heat_index_diff rain_intensity wind_category direction_label  \
0              5.9    Tidak Hujan        Tenang           Barat
1              4.9    Tidak Hujan        Tenang           Barat
2              4.6    Tidak Hujan        Tenang           Barat
3              4.6    Tidak Hujan        Tenang           Barat
4              4.4    Tidak Hujan        Tenang           Barat

   is_gust_extreme
0             True
1             True
2             True
3            False
4            False

## 3.5 Dimensi & Fact Table

In [13]:
# dim_date
def get_season(month):
    if month in [12,1,2]:   return "Musim Hujan Puncak"
    elif month in [3,4,5]:  return "Transisi 1"
    elif month in [6,7,8]:  return "Musim Kemarau"
    else:                   return "Transisi 2"

dates    = pd.to_datetime(df['date'].unique())
dim_date = pd.DataFrame({
    'date_id':     dates.strftime('%Y%m%d').astype(int),
    'full_date':   dates,
    'day':         dates.day,
    'month':       dates.month,
    'year':        dates.year,
    'quarter':     dates.quarter.map({1:'Q1',2:'Q2',3:'Q3',4:'Q4'}),
    'day_of_week': dates.day_name(),
    'is_weekend':  dates.day_of_week >= 5,
    'season':      dates.month.map(get_season)
})

# dim_time
def get_time_of_day(h):
    if h <= 5:    return "Dini Hari"
    elif h <= 11: return "Pagi"
    elif h <= 17: return "Siang"
    else:         return "Malam"

dim_time = pd.DataFrame({
    'time_id':      range(24),
    'hour':         range(24),
    'time_of_day':  [get_time_of_day(h) for h in range(24)],
    'is_peak_hour': [h in range(7,20) for h in range(24)]
})

# dim_location
CITIES_DIM = [
    {"city":"Surabaya",   "lat":-7.2575,  "lon":112.7521, "province":"Jawa Timur",       "island":"Jawa",       "timezone":"WIB",  "offset":7},
    {"city":"Jakarta",    "lat":-6.2088,  "lon":106.8456, "province":"DKI Jakarta",      "island":"Jawa",       "timezone":"WIB",  "offset":7},
    {"city":"Bandung",    "lat":-6.9175,  "lon":107.6191, "province":"Jawa Barat",       "island":"Jawa",       "timezone":"WIB",  "offset":7},
    {"city":"Medan",      "lat": 3.5952,  "lon": 98.6722, "province":"Sumatra Utara",    "island":"Sumatra",    "timezone":"WIB",  "offset":7},
    {"city":"Semarang",   "lat":-6.9932,  "lon":110.4229, "province":"Jawa Tengah",      "island":"Jawa",       "timezone":"WIB",  "offset":7},
    {"city":"Makassar",   "lat":-5.1477,  "lon":119.4327, "province":"Sulawesi Selatan", "island":"Sulawesi",   "timezone":"WITA", "offset":8},
    {"city":"Palembang",  "lat":-2.9761,  "lon":104.7754, "province":"Sumatra Selatan",  "island":"Sumatra",    "timezone":"WIB",  "offset":7},
    {"city":"Denpasar",   "lat":-8.6705,  "lon":115.2126, "province":"Bali",             "island":"Bali",       "timezone":"WITA", "offset":8},
    {"city":"Yogyakarta", "lat":-7.7956,  "lon":110.3695, "province":"DIY",              "island":"Jawa",       "timezone":"WIB",  "offset":7},
    {"city":"Balikpapan", "lat":-1.2675,  "lon":116.8289, "province":"Kalimantan Timur", "island":"Kalimantan", "timezone":"WITA", "offset":8},
]
dim_location = pd.DataFrame(CITIES_DIM).reset_index().rename(columns={'index':'location_id'})

# dim_weather_category
WMO_MAP = {
    0:("Cerah","Normal",False), 1:("Hampir Cerah","Normal",False),
    2:("Berawan Sebagian","Normal",False), 3:("Mendung","Normal",False),
    45:("Berkabut","Waspada",False), 48:("Kabut Beku","Waspada",False),
    51:("Gerimis Ringan","Normal",False), 61:("Hujan Ringan","Normal",False),
    63:("Hujan Sedang","Waspada",False), 65:("Hujan Lebat","Bahaya",True),
    80:("Hujan Lokal Ringan","Normal",False), 81:("Hujan Lokal Sedang","Waspada",False),
    82:("Hujan Lokal Ekstrem","Bahaya",True), 95:("Badai Petir","Bahaya",True),
    99:("Badai Petir Besar","Ekstrem",True),
}
dim_weather_category = pd.DataFrame([
    {"category_id":i, "weather_code":k, "description":v[0],
     "severity_level":v[1], "is_extreme":v[2]}
    for i,(k,v) in enumerate(WMO_MAP.items())
])

print(f'  Semua dimensi terbentuk!')
print(f'   dim_date             : {len(dim_date)} baris')
print(f'   dim_time             : {len(dim_time)} baris')
print(f'   dim_location         : {len(dim_location)} baris')
print(f'   dim_weather_category : {len(dim_weather_category)} baris')

  Semua dimensi terbentuk!
   dim_date             : 3653 baris
   dim_time             : 24 baris
   dim_location         : 10 baris
   dim_weather_category : 15 baris

In [14]:
# fact_weather

# FK date
df['date_id']      = pd.to_datetime(df['date']).dt.strftime('%Y%m%d').astype(int)
df['time_id']      = df['hour']

# FK location
loc_map            = dim_location.set_index('city')['location_id'].to_dict()
df['location_id']  = df['city'].map(loc_map)

# FK weather_cat
wmo_map            = dim_weather_category.set_index('weather_code')['category_id'].to_dict()
df['weather_cat_id'] = df['weather_code'].map(wmo_map)

FACT_COLS = [
    'date_id','time_id','location_id','weather_cat_id',
    'temperature_2m','apparent_temperature','relative_humidity_2m',
    'dew_point_2m','precipitation','rain','wind_speed_10m',
    'wind_direction_10m','wind_gusts_10m','cloud_cover',
    'shortwave_radiation','sunshine_duration','surface_pressure','weather_code',
    'heat_index_diff','rain_intensity','is_rainy_hour',
    'wind_category','direction_label','is_gust_extreme','alert_hour'
]
fact_weather = df[FACT_COLS].reset_index(drop=True)
fact_weather.index.name = 'fact_id'

print(f' fact_weather siap: {len(fact_weather):,} baris × {len(fact_weather.columns)} kolom')
display(fact_weather.head(3))

 fact_weather siap: 876,720 baris × 25 kolom

,date_id,time_id,location_id,weather_cat_id,temperature_2m,apparent_temperature,relative_humidity_2m,dew_point_2m,precipitation,rain,...,sunshine_duration,surface_pressure,weather_code,heat_index_diff,rain_intensity,is_rainy_hour,wind_category,direction_label,is_gust_extreme,alert_hour
fact_id,,,,,,,,,,,,,,,,,,,,,
0,20150101,0,9,3.0,24.6,30.5,99,24.5,0.0,0.0,...,0.0,999.3,3,5.9,Tidak Hujan,False,Tenang,Barat,True,0
1,20150101,1,9,3.0,25.4,30.3,88,23.3,0.0,0.0,...,0.0,998.3,3,4.9,Tidak Hujan,False,Tenang,Barat,True,0
2,20150101,2,9,3.0,25.4,30.0,87,23.0,0.0,0.0,...,0.0,997.8,3,4.6,Tidak Hujan,False,Tenang,Barat,True,0

# STEP 4 — Load ke Supabase

## 4.1 Koneksi

In [15]:
engine = create_engine(SUPABASE_URL)

with engine.connect() as conn:
    v = conn.execute(text("SELECT version()")).fetchone()[0]
    print(f'   Koneksi Supabase berhasil!')
    print(f'   PostgreSQL: {v[:40]}...')

   Koneksi Supabase berhasil!
   PostgreSQL: PostgreSQL 17.6 on aarch64-unknown-linux...

## 4.2 DDL — Buat Struktur Tabel di PostgreSQL

In [17]:
from sqlalchemy import text

DDL_SETUP = """
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

CREATE TABLE IF NOT EXISTS dim_date (
    date_id      INT PRIMARY KEY,
    full_date    DATE,
    day          INT, month INT, year INT,
    quarter      VARCHAR(2), day_of_week VARCHAR(10),
    is_weekend   BOOLEAN, season VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS dim_time (
    time_id      INT PRIMARY KEY,
    hour         INT,
    time_of_day  VARCHAR(15),
    is_peak_hour BOOLEAN
);

CREATE TABLE IF NOT EXISTS dim_location (
    location_id  INT PRIMARY KEY,
    city         VARCHAR(50), province VARCHAR(50),
    island       VARCHAR(30), timezone VARCHAR(10),
    latitude     FLOAT, longitude FLOAT,
    elevation    FLOAT, utc_offset INT
);

CREATE TABLE IF NOT EXISTS dim_weather_category (
    category_id    INT PRIMARY KEY,
    weather_code   INT,
    description    VARCHAR(50),
    severity_level VARCHAR(10),
    is_extreme     BOOLEAN
);

CREATE TABLE IF NOT EXISTS fact_weather (
    date_id              INT NOT NULL,
    time_id              INT,
    location_id          INT,
    weather_cat_id       INT,
    temperature_2m       FLOAT, apparent_temperature FLOAT,
    relative_humidity_2m FLOAT, dew_point_2m FLOAT,
    precipitation        FLOAT, rain FLOAT,
    cloud_cover          FLOAT, wind_speed_10m FLOAT,
    wind_direction_10m   FLOAT, wind_gusts_10m FLOAT,
    shortwave_radiation  FLOAT, sunshine_duration FLOAT,
    surface_pressure     FLOAT, weather_code INT,
    heat_index_diff      FLOAT,
    rain_intensity       VARCHAR(20), is_rainy_hour BOOLEAN,
    wind_category        VARCHAR(15), direction_label VARCHAR(10),
    is_gust_extreme      BOOLEAN, alert_hour INT,
    PRIMARY KEY (date_id, time_id, location_id)
) PARTITION BY RANGE (date_id);

CREATE TABLE IF NOT EXISTS fact_weather_2015
    PARTITION OF fact_weather FOR VALUES FROM (20150101) TO (20160101);
CREATE TABLE IF NOT EXISTS fact_weather_2016
    PARTITION OF fact_weather FOR VALUES FROM (20160101) TO (20170101);
CREATE TABLE IF NOT EXISTS fact_weather_2017
    PARTITION OF fact_weather FOR VALUES FROM (20170101) TO (20180101);
CREATE TABLE IF NOT EXISTS fact_weather_2018
    PARTITION OF fact_weather FOR VALUES FROM (20180101) TO (20190101);
CREATE TABLE IF NOT EXISTS fact_weather_2019
    PARTITION OF fact_weather FOR VALUES FROM (20190101) TO (20200101);
CREATE TABLE IF NOT EXISTS fact_weather_2020
    PARTITION OF fact_weather FOR VALUES FROM (20200101) TO (20210101);
CREATE TABLE IF NOT EXISTS fact_weather_2021
    PARTITION OF fact_weather FOR VALUES FROM (20210101) TO (20220101);
CREATE TABLE IF NOT EXISTS fact_weather_2022
    PARTITION OF fact_weather FOR VALUES FROM (20220101) TO (20230101);
CREATE TABLE IF NOT EXISTS fact_weather_2023
    PARTITION OF fact_weather FOR VALUES FROM (20230101) TO (20240101);
CREATE TABLE IF NOT EXISTS fact_weather_2024
    PARTITION OF fact_weather FOR VALUES FROM (20240101) TO (20250101);
CREATE TABLE IF NOT EXISTS fact_weather_2025
    PARTITION OF fact_weather FOR VALUES FROM (20250101) TO (20260101);
CREATE TABLE IF NOT EXISTS fact_weather_2026
    PARTITION OF fact_weather FOR VALUES FROM (20260101) TO (20270101);

CREATE INDEX IF NOT EXISTS idx_fw_location ON fact_weather (location_id);
CREATE INDEX IF NOT EXISTS idx_fw_date     ON fact_weather (date_id);
CREATE INDEX IF NOT EXISTS idx_fw_alert    ON fact_weather (alert_hour) WHERE alert_hour = 1;

CREATE TABLE IF NOT EXISTS etl_state (
    id        INT PRIMARY KEY DEFAULT 1,
    run_ke    INT DEFAULT 0,
    minggu_ke INT DEFAULT 0,
    last_run  TIMESTAMP
);

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_daily_summary AS
SELECT
    d.full_date::date AS date,
    d.year, d.month, d.quarter,
    l.city, l.island, l.province,
    ROUND(AVG(f.temperature_2m)::numeric, 2)       AS avg_temp,
    ROUND(MAX(f.temperature_2m)::numeric, 2)       AS max_temp,
    ROUND(MIN(f.temperature_2m)::numeric, 2)       AS min_temp,
    ROUND(SUM(f.precipitation)::numeric, 2)        AS total_precip,
    ROUND(AVG(f.relative_humidity_2m)::numeric, 2) AS avg_humidity,
    ROUND(AVG(f.wind_speed_10m)::numeric, 2)       AS avg_wind,
    SUM(f.alert_hour)                              AS jam_alert,
    COUNT(*) FILTER (WHERE f.is_rainy_hour)        AS jam_hujan
FROM fact_weather f
JOIN dim_date     d ON f.date_id     = d.date_id
JOIN dim_location l ON f.location_id = l.location_id
GROUP BY d.full_date, d.year, d.month, d.quarter, l.city, l.island, l.province
WITH NO DATA;

CREATE UNIQUE INDEX IF NOT EXISTS uix_mvds ON mv_daily_summary (date, city);

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_monthly_avg AS
SELECT
    d.year, d.month, l.city, l.island,
    ROUND(AVG(f.temperature_2m)::numeric, 2)       AS avg_temp,
    ROUND(SUM(f.precipitation)::numeric, 2)        AS total_precip,
    ROUND(AVG(f.relative_humidity_2m)::numeric, 2) AS avg_humidity,
    COUNT(DISTINCT d.date_id)                      AS hari_data
FROM fact_weather f
JOIN dim_date     d ON f.date_id     = d.date_id
JOIN dim_location l ON f.location_id = l.location_id
GROUP BY d.year, d.month, l.city, l.island
WITH NO DATA;

CREATE UNIQUE INDEX IF NOT EXISTS uix_mvma ON mv_monthly_avg (year, month, city);
"""

with engine.connect() as conn:
    conn.exec_driver_sql(DDL_SETUP)
    conn.commit()
    print("DDL selesai — semua tabel siap")

DDL selesai — semua tabel siap

## 4.3 Load Data (to_sql)

In [18]:
import time

def upsert_dim_date(df, engine):
    existing = pd.read_sql("SELECT date_id FROM dim_date", engine)
    new_rows = df[~df['date_id'].isin(existing['date_id'])]
    if len(new_rows) == 0:
        print("  dim_date: tidak ada tanggal baru, skip")
        return
    new_rows.to_sql('dim_date', engine, if_exists='append', index=False)
    print(f"  dim_date: +{len(new_rows)} baris")

def upsert_dim_static(df, tbl_name, engine):
    with engine.connect() as conn:
        count = conn.execute(text(f"SELECT COUNT(*) FROM {tbl_name}")).scalar()
    if count > 0:
        print(f"  {tbl_name}: sudah ada data ({count} baris), skip")
        return
    df.to_sql(tbl_name, engine, if_exists='append', index=False)
    print(f"  {tbl_name}: +{len(df)} baris")

def load_fact_safe(df, engine, chunksize=5000):
    # Rename kolom biar cocok dengan DDL etl_runner
    df = df.rename(columns={'lat': 'latitude', 'lon': 'longitude'}) if 'lat' in df.columns else df

    min_id = int(df['date_id'].min())
    max_id = int(df['date_id'].max())
    print(f"  fact_weather: DELETE range {min_id} – {max_id}...")

    with engine.connect() as conn:
        conn.execute(text(
            "DELETE FROM fact_weather WHERE date_id BETWEEN :s AND :e"
        ), {"s": min_id, "e": max_id})
        conn.commit()

    start = time.time()
    df.to_sql('fact_weather', engine, if_exists='append', index=False, chunksize=chunksize, method='multi')
    print(f"  fact_weather: +{len(df):,} baris ({time.time()-start:.1f}s)")

# Rename kolom dim_location biar cocok
dim_location_load = dim_location.rename(columns={
    'offset': 'utc_offset',
    'lat': 'latitude',
    'lon': 'longitude'
})

upsert_dim_date(dim_date, engine)
upsert_dim_static(dim_time, 'dim_time', engine)
upsert_dim_static(dim_location_load, 'dim_location', engine)
upsert_dim_static(dim_weather_category, 'dim_weather_category', engine)
load_fact_safe(fact_weather, engine)

print('\nSemua tabel berhasil di-load!')

  dim_date: tidak ada tanggal baru, skip
  dim_time: sudah ada data (24 baris), skip
  dim_location: sudah ada data (10 baris), skip
  dim_weather_category: sudah ada data (15 baris), skip
  fact_weather: DELETE range 20150101 – 20241231...
  fact_weather: +876,720 baris (775.1s)

Semua tabel berhasil di-load!

## 4.4 Verifikasi Load

In [19]:
print('='*55)
print('VERIFIKASI LOAD KE SUPABASE')
print('='*55)

tables = ['dim_date','dim_time','dim_location','dim_weather_category','fact_weather']
expected = {
    'dim_date':             len(dim_date),
    'dim_time':             len(dim_time),
    'dim_location':         len(dim_location),
    'dim_weather_category': len(dim_weather_category),
    'fact_weather':         len(fact_weather),
}

with engine.connect() as conn:
    print(f"{'Tabel':<25} {'Di DB':>10} {'Di DF':>10} {'Status':>8}")
    print('-'*55)
    for tbl in tables:
        count_db = conn.execute(text(f"SELECT COUNT(*) FROM {tbl}")).fetchone()[0]
        count_df = expected[tbl]
        ok = '✅' if count_db == count_df else '⚠️'
        print(f"{tbl:<25} {count_db:>10,} {count_df:>10,} {ok:>8}")

    # Cek duplikat di fact_weather
    print('\nCek duplikat fact_weather (date_id + time_id + location_id):')
    dup = conn.execute(text("""
        SELECT COUNT(*) FROM (
            SELECT date_id, time_id, location_id, COUNT(*)
            FROM fact_weather
            GROUP BY date_id, time_id, location_id
            HAVING COUNT(*) > 1
        ) t
    """)).fetchone()[0]
    print(f'  Baris duplikat: {dup} {"✅" if dup == 0 else "⚠️ Ada duplikat!"}')

    # Cek partisi
    print('\nPartisi yang ada:')
    parts = conn.execute(text("""
        SELECT relname, pg_size_pretty(pg_relation_size(oid)) AS ukuran
        FROM pg_class
        WHERE relname LIKE 'fact_weather_2%'
        ORDER BY relname
    """)).fetchall()
    for p in parts:
        print(f'  {p[0]:<30} {p[1]}')

=======================================================
VERIFIKASI LOAD KE SUPABASE
=======================================================
Tabel                          Di DB      Di DF   Status
-------------------------------------------------------
dim_date                       3,702      3,653       ⚠️
dim_time                          24         24        ✅
dim_location                      10         10        ✅
dim_weather_category              15         15        ✅
fact_weather                 888,480    876,720       ⚠️

Cek duplikat fact_weather (date_id + time_id + location_id):
  Baris duplikat: 0 ✅

Partisi yang ada:
  fact_weather_2015              14 MB
  fact_weather_2015_alert_hour_idx 872 kB
  fact_weather_2015_date_id_idx  792 kB
  fact_weather_2015_location_id_idx 744 kB
  fact_weather_2015_pkey         3512 kB
  fact_weather_2015_precipitation_idx 2800 kB
  fact_weather_2015_time_id_idx  592 kB
  fact_weather_2015_weather_cat_id_idx 864 kB
  fact_weather_2016              14 MB
  fact_weather_2016_alert_hour_idx 880 kB
  fact_weather_2016_date_id_idx  800 kB
  fact_weather_2016_location_id_idx 744 kB
  fact_weather_2016_pkey         3520 kB
  fact_weather_2016_precipitation_idx 2768 kB
  fact_weather_2016_time_id_idx  592 kB
  fact_weather_2016_weather_cat_id_idx 856 kB
  fact_weather_2017              14 MB
  fact_weather_2017_alert_hour_idx 888 kB
  fact_weather_2017_date_id_idx  792 kB
  fact_weather_2017_location_id_idx 744 kB
  fact_weather_2017_pkey         3512 kB
  fact_weather_2017_precipitation_idx 2816 kB
  fact_weather_2017_time_id_idx  592 kB
  fact_weather_2017_weather_cat_id_idx 872 kB
  fact_weather_2018              14 MB
  fact_weather_2018_alert_hour_idx 888 kB
  fact_weather_2018_date_id_idx  936 kB
  fact_weather_2018_location_id_idx 776 kB
  fact_weather_2018_pkey         3512 kB
  fact_weather_2018_precipitation_idx 2816 kB
  fact_weather_2018_time_id_idx  592 kB
  fact_weather_2018_weather_cat_id_idx 864 kB
  fact_weather_2019              14 MB
  fact_weather_2019_alert_hour_idx 720 kB
  fact_weather_2019_date_id_idx  1048 kB
  fact_weather_2019_location_id_idx 736 kB
  fact_weather_2019_pkey         3504 kB
  fact_weather_2019_precipitation_idx 2480 kB
  fact_weather_2019_time_id_idx  776 kB
  fact_weather_2019_weather_cat_id_idx 792 kB
  fact_weather_2020              14 MB
  fact_weather_2020_alert_hour_idx 728 kB
  fact_weather_2020_date_id_idx  1056 kB
  fact_weather_2020_location_id_idx 736 kB
  fact_weather_2020_pkey         3512 kB
  fact_weather_2020_precipitation_idx 2504 kB
  fact_weather_2020_time_id_idx  776 kB
  fact_weather_2020_weather_cat_id_idx 784 kB
  fact_weather_2021              14 MB
  fact_weather_2021_alert_hour_idx 712 kB
  fact_weather_2021_date_id_idx  1048 kB
  fact_weather_2021_location_id_idx 736 kB
  fact_weather_2021_pkey         3504 kB
  fact_weather_2021_precipitation_idx 2480 kB
  fact_weather_2021_time_id_idx  776 kB
  fact_weather_2021_weather_cat_id_idx 768 kB
  fact_weather_2022              14 MB
  fact_weather_2022_alert_hour_idx 736 kB
  fact_weather_2022_date_id_idx  1048 kB
  fact_weather_2022_location_id_idx 736 kB
  fact_weather_2022_pkey         3504 kB
  fact_weather_2022_precipitation_idx 2504 kB
  fact_weather_2022_time_id_idx  776 kB
  fact_weather_2022_weather_cat_id_idx 808 kB
  fact_weather_2023              14 MB
  fact_weather_2023_alert_hour_idx 728 kB
  fact_weather_2023_date_id_idx  1048 kB
  fact_weather_2023_location_id_idx 736 kB
  fact_weather_2023_pkey         3504 kB
  fact_weather_2023_precipitation_idx 2464 kB
  fact_weather_2023_time_id_idx  776 kB
  fact_weather_2023_weather_cat_id_idx 784 kB
  fact_weather_2024              14 MB
  fact_weather_2024_alert_hour_idx 912 kB
  fact_weather_2024_date_id_idx  1056 kB
  fact_weather_2024_location_id_idx 768 kB
  fact_weather_2024_pkey         3584 kB
  fact_weather_2024_precipitation_idx 3088 kB
  fact_weather_2024_time_id_idx  776 kB
  fact_weather_2024_weather_cat_id_idx 912 kB
  fact_weather_2025              1872 kB
  fact_weather_2025_alert_hour_idx 96 kB
  fact_weather_2025_date_id_idx  136 kB
  fact_weather_2025_location_id_idx 96 kB
  fact_weather_2025_pkey         376 kB
  fact_weather_2025_precipitation_idx 304 kB
  fact_weather_2025_time_id_idx  136 kB
  fact_weather_2025_weather_cat_id_idx 104 kB
  fact_weather_2026              0 bytes
  fact_weather_2026_alert_hour_idx 8192 bytes
  fact_weather_2026_date_id_idx  8192 bytes
  fact_weather_2026_location_id_idx 8192 bytes
  fact_weather_2026_pkey         8192 bytes
  fact_weather_2026_precipitation_idx 8192 bytes
  fact_weather_2026_time_id_idx  8192 bytes
  fact_weather_2026_weather_cat_id_idx 8192 bytes

⚠️ muncul karena ada selisih di dim_date dan fact_weather, selisih tersebut karena di supabase saat ini sudah terdapat data hasil async 2025 yang ada pada github